# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry shell
        poetry install
      with:
        options: "--check --verbose"
    - name: Lint with ruff & black
      run: |
        # stop the build if there are Python PEP 8 problems
        black --check .
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ruff check .
    - name: Test with pytest
      run: |
        pytest
